/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

function NodeIcon(props) {
  const { nodes, materials } = useGLTF('/node-logo.glb')
  return (
    <group {...props} dispose={null}>
      <group scale={1.612}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube011.geometry}
          material={materials['Material.044']}
          rotation={[Math.PI, 0, Math.PI]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve003.geometry}
          material={materials['Material.001']}
          position={[0, -0.066, 0.095]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={5.154}
        />
      </group>
    </group>
  )
}

useGLTF.preload('/node-logo.glb')

export default NodeIcon