/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react';
import { useGLTF } from '@react-three/drei';

function ReactLogo(props) {
  const { nodes, materials } = useGLTF('/reactLogo.glb');
  return (
    <group {...props} dispose={null}>
      <group position={[0, 0, -0.12]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Sphere.geometry}
          material={materials['Material.001']}
          position={[0, 0.011, -0.378]}
          scale={0.05}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Torus002.geometry}
          material={materials['Material.001']}
          position={[0, 0.011, -0.37]}
          rotation={[-Math.PI / 2, 1.043, -1.981]}
          scale={0.266}
        />
      </group>
    </group>
  );
}

export default ReactLogo;

useGLTF.preload('/reactLogo.glb');
