/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: kenny_pizza (https://sketchfab.com/kenny_pizza)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/low-poly-coffee-cup-6e6432980e0944219434b81cbc67eacb
Title: Low Poly Coffee Cup
*/

import React, { useRef } from 'react';
import { useGLTF } from '@react-three/drei';

function Coffee(props) {
  const { nodes, materials } = useGLTF('/low_poly_coffee_cup/scene.gltf');
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group position={[0.391, 0, 0]} rotation={[Math.PI / 2, 0, 0]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cylinder_0.geometry}
            // material={materials.Porcelain}
          >
            <meshStandardMaterial color={0xffffff} />
          </mesh>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cylinder_1.geometry}
            material={materials.Coffee}></mesh>
        </group>
      </group>
    </group>
  );
}

export default Coffee;

useGLTF.preload('/low_poly_coffee_cup/scene.gltf');
