/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: pythonreaper (https://sketchfab.com/minasianjoey)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/low-poly-laptop-646d3c0318f9451a8e4fce2798072aa6
Title: Low Poly Laptop
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

function Laptop(props) {
  const { nodes, materials } = useGLTF('/low_poly_laptop/scene.gltf')
  return (
    <group {...props} dispose={null}>
      <group scale={0.01}>
        <group
          position={[-640.757, 638.489, 0]}
          rotation={[-Math.PI / 2, Math.PI / 2, 0]}
          scale={[591.712, 951.182, 49.909]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube001_Material001_0.geometry}
            material={materials['Material.001']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube001_Material_0.geometry}
            material={materials.Material}
          />
        </group>
        <group
          position={[-589.005, 47.149, 958.996]}
          rotation={[-Math.PI / 2, Math.PI / 2, 0]}
          scale={[705.172, 951.182, 49.909]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube002_Material001_0.geometry}
            material={materials['Material.001']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube002_Material_0.geometry}
            material={materials.Material}
          />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/low_poly_laptop/scene.gltf')

export default Laptop